### ISSUE TITLE
wavedrom-rs won't build

### ISSUE THREAD

**Issue by johnblommers** [coastalwhite/wavedrom-rs#1]
It won't build because it's using an unstable library feature:

- `once_cell`
- `nonzero_min_max`

The `cargo install mdbook-wavedrom-rs` command itself also appears to pull in Rust 1.67.1 but we're at version 1.70 now.

Am I missing an incantation?

Yes, I am! It appears we need to use the nightly build of Rust to use unstable features:

```bash
rustup override set nightly
cargo install mdbook-wavedrom-rs
```

**Comment by coastalwhite** [comment]
Thank you for this feedback. I'll add a note to the README.

You don't need nightly, you need to use version `1.70` to compile.

```bash
rustup default 1.70
cargo install wavedrom-rs
cargo install mdbook-wavedrom-rs
```

**Comment by coastalwhite** [comment]
I've added a note to the README.
